name: ds
channels:
 - conda-forge

dependencies:
 - bokeh
 - cartopy
 - colorcet
 - conda-lock
 - graphviz
 - python-graphviz
 - dask
 - datashader
 - distributed
 - fastparquet
 - holoviews
 - ipython
 - jupyter
 - matplotlib
 - micromamba
 - networkx>=2.0
 - numba
 - numpy
 - pandas >=0.24.1
 - param
 - python-snappy
 - python
 - rasterio
 - requests
 - scikit-image
 - scikit-learn
 - scipy
 - shapely
 - snappy
 - statsmodels
 - streamz
 - xarray
 - ipympl
 - voila>=0.4.0
 - jupyterlab>=3.1
 - ipywidgets
 - seaborn
