name: ds
channels:
 - conda-forge

dependencies:
 - ipython
 - jupyter
 - matplotlib
 - networkx>=2.0
 - numpy
 - pandas >=0.24.1
 - param
 - python
 - scikit-image
 - scikit-learn
 - scipy
 - xarray
 - ipympl
 - voila>=0.4.0
 - jupyterlab>=3.1
 - ipywidgets
 - seaborn
